// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:shiftsnap/models/scanned_roster.dart';
import 'package:shiftsnap/models/shift.dart';
import 'package:shiftsnap/models/user_preferences.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ScannedRosterAdapter());
    registerAdapter(ShiftAdapter());
    registerAdapter(UserPreferencesAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ScannedRosterAdapter());
    registerAdapter(ShiftAdapter());
    registerAdapter(UserPreferencesAdapter());
  }
}
